app:
  name: "ACL Casbin App"
  version: "1.0.0"
  port: 8080
  host: "localhost"

mongo:
  hosts:
    - 127.0.0.1
  username: ""
  password: ""
  port: "27017"
  protocol: "mongodb"
  db_name: "acl_db"
  collection: "users"
  auth_source: "admin"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: "0"
  dial_timeout: "5s"
  read_timeout: "3s"
  write_timeout: "3s"
  idle_check_frequency: "1m"
  pool_size: 10
  pool_timeout: "5s"

rate_limiter:
  rate: "10"
  bursts: 5

token:
  expiry_access_token: "15m"
  expiry_refresh_token: "24h"
  secret_key: "your-secret-key-here"

logger:
  file_path: "logs/app.log"
  encoding: "json"
  level: "info"
  logger_name: "ACL-Logger"
