// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"acl-casbin/controller"
	"acl-casbin/repository"
	"github.com/casbin/casbin/v2"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitializeApp(secret string) (*App, error) {
	client := ProvideMongoClient()
	enforcer := ProvideCasbinEnforcer(client)
	database := ProvideDatabase(client)
	userRepository := ProvideUserRepository(database)
	refreshTokenRepository := ProvideRefreshTokenRepository(database)
	jwtToken := ProvideJWT(secret)
	authService := ProvideAuthService(userRepository, refreshTokenRepository, jwtToken)
	authController := ProvideAuthController(authService)
	userService := ProvideUserService(userRepository)
	userController := ProvideUserController(userService)
	app := &App{
		Mongo:    client,
		Enforcer: enforcer,
		AuthCtrl: authController,
		UserCtrl: userController,
		UserRepo: userRepository,
	}
	return app, nil
}

// wire.go:

type App struct {
	Mongo    *mongo.Client
	Enforcer *casbin.Enforcer
	AuthCtrl controller.AuthController
	UserCtrl controller.UserController
	UserRepo repository.UserRepository
}
