// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"acl-casbin/controller"
	"acl-casbin/repository"
	"acl-casbin/service"
	"acl-casbin/utils"
	"github.com/casbin/casbin/v2"
	"github.com/gin-gonic/gin"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func InitializeApp(secret string) (*App, error) {
	client := ProvideMongoClient()
	enforcer := ProvideCasbinEnforcer(client)
	database := ProvideDatabase(client)
	userRepository := ProvideUserRepository(database)
	refreshTokenRepository := ProvideRefreshTokenRepository(database)
	jwtToken := ProvideJWT(secret)
	blackListTokenRepository := ProviderBlackListRepository(database)
	authService := ProvideAuthService(userRepository, refreshTokenRepository, jwtToken, blackListTokenRepository)
	userService := ProvideUserService(userRepository)
	authController := ProvideAuthController(authService, userService)
	userController := ProvideUserController(userService)
	approvalRepository := ProviderApprovalRepository(database)
	approvalService := ProviderApprovalService(approvalRepository)
	approvalController := ProviderApprovalController(approvalService)
	casbinRepository := ProviderCasbinRepository(enforcer)
	casbinService := ProviderCasbinService(casbinRepository)
	casbinController := ProviderCasbinController(casbinService)
	engine := ProviderGinEngine()
	routeController := ProviderRouterController(engine)
	app := &App{
		Mongo:            client,
		Enforcer:         enforcer,
		AuthCtrl:         authController,
		UserCtrl:         userController,
		UserRepo:         userRepository,
		RefreshTokenRepo: refreshTokenRepository,
		ApproveCtrl:      approvalController,
		ApproveRepo:      approvalRepository,
		BlackListRepo:    blackListTokenRepository,
		TokenManager:     jwtToken,
		CasbinRepo:       casbinRepository,
		CasbinCtrl:       casbinController,
		CasbinService:    casbinService,
		RouterCtr:        routeController,
		Engine:           engine,
	}
	return app, nil
}

// wire.go:

type App struct {
	Mongo            *mongo.Client
	Enforcer         *casbin.Enforcer
	AuthCtrl         controller.AuthController
	RefreshTokenRepo repository.RefreshTokenRepository
	UserCtrl         controller.UserController
	UserRepo         repository.UserRepository
	ApproveCtrl      controller.ApprovalController
	ApproveRepo      repository.ApprovalRepository
	BlackListRepo    repository.BlackListTokenRepository
	TokenManager     utils.JwtToken
	CasbinRepo       repository.CasbinRepository
	CasbinCtrl       controller.CasbinController
	CasbinService    service.CasbinService
	RouterCtr        controller.RouteController
	Engine           *gin.Engine
}
